name: Docker Image CI

on:
  push:
    branches: [ master ]
  
jobs:

  build:

    runs-on: [self-hosted]

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - name: Login to Docker Registry
      uses: ${{ docker_url }}
      with:
        username: ${{ docker_username }}
        password: ${{ docker_password }}
    -
       name: Build and push
       id: docker_build
       uses: docker/build-push-action@v2
       with:
         context: .
         file: ./Dockerfile
         platforms: linux/amd64,linux/arm64,linux/386
         push: true
         tags: user/fedora32:latest
